### PR TITLE
Use correct hostname for longpoll_delta

### PR DESCRIPTION
**Pull request by tgjones**

### CODE REVIEW

**Comment by JanZeman** [comment]
Hello, I got contacted by DropBox regarding exactly this issue. They say they plan to remove the /longpoll_delta functionality from api.dropbox.com on October 20, 2015. So I am voting for early approval of this PR and hopefully an early release. Thank you. Jan

**Comment by JanZeman** [comment]
Thank you! Can I please ask when I can expect this change available via NuGet package update?

**Comment by JanZeman** [comment]
Hi @dkarzon ,  it is now 6 weeks, could you please try to reply my question?  I tried to send an email both to you and @tgjones and got answer from him, that he is just a user as me and you could be the one who is able to create the release. I can also see you merged it to master. @tgjones told me he is also waiting for the new NuGet. I hope/guess it should not be that much work to create one, should it? Or can you point me to anybody who is normally responsible for new NuGet releases? Thank you so much in advance!  All the best, Jan

**Comment by dkarzon** [comment]
@JanZeman Sorry for taking so long, I have updated the package in NuGet to v1.5.20 with the latest https://www.nuget.org/packages/DropNetRT/1.5.20

Would you be interested in becoming a contributor on the project?

**Comment by JanZeman** [comment]
@dkarzon That's wonderful! Thank you very much :) I will pick it up immediately. And.. sure, I am used to contribute where I can. Usually rather smaller PRs for github projects and as I am not very experienced DropBox API programmer it could be rather something smaller in this project too. If I bump into situation where I can contribute it would be my pleasure.

**Pull request merged**
